name: danger
on:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened, ready_for_review]

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Danger
        uses: danger/danger@9.5.0

    env:
      DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
